# Generated by Django 3.2.3 on 2021-05-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dar',
            name='title',
        ),
        migrations.AddField(
            model_name='dar',
            name='additional_comments',
            field=models.TextField(default='Any addional comments?'),
        ),
        migrations.AddField(
            model_name='dar',
            name='bascketball_court',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dar',
            name='big_pool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dar',
            name='club_house',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dar',
            name='entrace_back_gate',
            field=models.CharField(default='SLOW', max_length=50),
        ),
        migrations.AddField(
            model_name='dar',
            name='exit_back_gate',
            field=models.CharField(default='SLOW', max_length=50),
        ),
        migrations.AddField(
            model_name='dar',
            name='exit_front_gate',
            field=models.CharField(default='SLOW', max_length=50),
        ),
        migrations.AddField(
            model_name='dar',
            name='gym',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dar',
            name='resident_front_gate',
            field=models.CharField(default='SLOW', max_length=50),
        ),
        migrations.AddField(
            model_name='dar',
            name='small_pool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dar',
            name='tennis_court',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dar',
            name='time',
            field=models.CharField(default='13:00', max_length=50),
        ),
        migrations.AddField(
            model_name='dar',
            name='visitor_front_gate',
            field=models.CharField(default='SLOW', max_length=50),
        ),
    ]
