# Generated by Django 3.2.3 on 2021-05-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210523_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dar',
            name='additional_comments',
            field=models.TextField(blank=True, default='Any addional comments?'),
        ),
        migrations.AlterField(
            model_name='dar',
            name='bascketball_court',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dar',
            name='big_pool',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dar',
            name='club_house',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dar',
            name='gym',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dar',
            name='small_pool',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dar',
            name='tennis_court',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
