# Generated by Django 3.2.3 on 2021-05-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20210523_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='DARAdditionalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_comments', models.TextField(blank=True, default='Any addional comments?')),
            ],
        ),
        migrations.RemoveField(
            model_name='dar',
            name='additional_comments',
        ),
    ]
