# Generated by Django 3.2.3 on 2021-05-24 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20210523_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DARAdditionalComment',
        ),
    ]
