# Generated by Django 3.2.3 on 2021-05-24 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_daradditionalcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dar',
            old_name='big_pool',
            new_name='pool',
        ),
        migrations.RemoveField(
            model_name='dar',
            name='small_pool',
        ),
    ]
