# Generated by Django 3.2.3 on 2021-05-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20210524_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='dar',
            name='officer_to_relieve',
            field=models.CharField(default='Burchfield', max_length=30),
        ),
        migrations.AlterField(
            model_name='dar',
            name='bascketball_court',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dar',
            name='club_house',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dar',
            name='entrace_back_gate',
            field=models.CharField(default='slow', max_length=50),
        ),
        migrations.AlterField(
            model_name='dar',
            name='exit_back_gate',
            field=models.CharField(default='slow', max_length=50),
        ),
        migrations.AlterField(
            model_name='dar',
            name='exit_front_gate',
            field=models.CharField(default='slow', max_length=50),
        ),
        migrations.AlterField(
            model_name='dar',
            name='gym',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dar',
            name='pool',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dar',
            name='resident_front_gate',
            field=models.CharField(default='slow', max_length=50),
        ),
        migrations.AlterField(
            model_name='dar',
            name='tennis_court',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dar',
            name='visitor_front_gate',
            field=models.CharField(default='slow', max_length=50),
        ),
        migrations.AlterField(
            model_name='daradditionalcomment',
            name='additional_comments',
            field=models.TextField(default='Any addional comments?'),
        ),
    ]
