# Generated by Django 3.2.3 on 2021-05-24 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20210524_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='daradditionalcomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
