# Generated by Django 3.2.3 on 2021-05-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_alter_daradditionalcomment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daradditionalcomment',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
