# Generated by Django 3.2.3 on 2021-05-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20210524_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dar',
            name='gym',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
