# Generated by Django 3.2.3 on 2021-05-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_alter_dar_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dar',
            name='gym',
            field=models.IntegerField(blank=True),
        ),
    ]
