# Generated by Django 3.2.3 on 2021-05-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_alter_dar_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dar',
            name='bascketball_court',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dar',
            name='club_house',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dar',
            name='entrace_back_gate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dar',
            name='exit_back_gate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dar',
            name='exit_front_gate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dar',
            name='pool',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dar',
            name='resident_front_gate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dar',
            name='tennis_court',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dar',
            name='visitor_front_gate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
