# Generated by Django 3.2.3 on 2021-05-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_auto_20210524_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='dar',
            name='officer_to_relieve',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
