# Generated by Django 3.2.3 on 2021-05-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_dar_officer_to_relieve'),
    ]

    operations = [
        migrations.AddField(
            model_name='dar',
            name='additional_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
