# Generated by Django 3.2.3 on 2021-05-25 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_dar_officer_relieved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dar',
            old_name='officer_to_relieve',
            new_name='officer_relieving',
        ),
    ]
