# Generated by Django 3.2.3 on 2021-05-25 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0021_rename_officer_to_relieve_dar_officer_relieving'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DARAdditionalComment',
        ),
    ]
