# Generated by Django 3.2.3 on 2021-05-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0022_delete_daradditionalcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dar',
            name='cameras_not_working',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dar',
            name='gates_not_working',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dar',
            name='gatesarms_not_working',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
