# Generated by Django 3.2.3 on 2021-05-25 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0024_rename_gatesarms_not_working_dar_gates_arms_not_working'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dar',
            old_name='gates_arms_not_working',
            new_name='gate_arms_not_working',
        ),
    ]
