# Generated by Django 3.2.3 on 2021-05-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0025_rename_gates_arms_not_working_dar_gate_arms_not_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dar',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
