# Generated by Django 3.2.3 on 2021-05-30 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0026_alter_dar_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dar',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
