# Generated by Django 3.2.3 on 2021-06-02 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0028_end_of_shift_dar'),
    ]

    operations = [
        migrations.AddField(
            model_name='end_of_shift_dar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
